### ISSUE TITLE
[sockets] track socket errors

### ISSUE THREAD

**Issue by b-ma** [collective-soundworks/soundworks#30]
While this is not a blocking issue, this is not clean and triggers lots of error messages.

_note:_ Find a way to programmatically reproduce the problem, to make sure to track down all possible implications (ghost states, etc.)

**Comment by b-ma** [comment]
see https://github.com/collective-soundworks/soundworks/commit/e0605773ff9c7929ef6baf4ceb8676c047fc6a14, (hopefully fixed)

**Comment by b-ma** [comment]
should do proper tests anyway

**Comment by b-ma** [comment]
ok it's not...

```sh
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writevGeneric (internal/stream_base_commons.js:139:3)
    at Socket._writeGeneric (net.js:783:11)
    at Socket._writev (net.js:792:8)
    at doWrite (internal/streams/writable.js:375:12)
    at clearBuffer (internal/streams/writable.js:521:5)
    at Socket.Writable.uncork (internal/streams/writable.js:317:7)
    at Sender.sendFrame (node_modules/ws/lib/sender.js:398:20)
    at Sender.send (node_modules/ws/lib/sender.js:294:12)
    at WebSocket.send (node_modules/ws/lib/websocket.js:361:18) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

see https://github.com/websockets/ws/issues/1172

**Comment by b-ma** [comment]
seems to reproduce when we have minimum 6 emulated clients (i.e. 12 opened sockets) and reload the page
